########################################################################################
###################            https://clxrity.xyz             #########################
########################################################################################

########################################################################################
###################                  1.0-SNAPSHOT              #########################
########################################################################################

########################################################################################
# SimpleHealing is designed to work alongside Essentials & permissionsEx               #
# If using Essentials, add /heal & /feed to the disabled commands list in config.yml   #
########################################################################################

########################################################################################
#########          Made for mineverse.com | https://mineverse.com              #########
########################################################################################

#### !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ####
#### As of 1.0-SNAPSHOT -- Configuration is not... configured... Changing these values will not change anything. ####
#### !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ####

########## /heal | simplehealing.heal #########

# Cooldown for /heal (seconds)
heal-cooldown: 60

# If 'true': the permission 'simplehealing.heal' will allow healing others
# If 'false': the permission 'simplehealing.heal' will not allow healing others
heal-others: true

# If 'op': anyone who isn't op will need the permission manually given to access /heal
# If 'false': no one can access /heal without the permission
# If 'true': anyone can access /heal
# !!!!! Recommended to keep at 'op'
heal-default: op

# If 'true': /heal will remove burning affects
# If 'false': /heal won't remove burning affects
heal-remove-burning: true

########## /feed | simplehealing.feed ##########

# Cooldown for /feed (seconds)
feed-cooldown: 60

# If 'true': the permission 'simplehealing.feed' will allow feeding others
# If 'false': the permission 'simplehealing.feed' will not allow feeding others
feed-others: true

# If 'op': anyone who isn't op will need the permission manually given to access /feed
# If 'false': no one can access /feed without the permission
# If 'true': anyone can access /feed
# !!!!! Recommended to keep at 'op'
feed-default: op

######### BOTH #########

# If 'true': both /heal & /feed will have the same cooldown
# If 'false': /heal & /feed will have a separate cooldown
connected-cooldown: false



